import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const vazirmatn = localFont({
  src: "../public/fonts/Vazirmatn/Vazirmatn-Regular.ttf",
  display: "swap",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html dir="rtl" lang="en">
      <body className={`${vazirmatn.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
