import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "./src/components/shared/layout/Header/Header";
import Footer from "./src/components/shared/layout/Footer/Footer";
import MobileBottomBar from "./src/components/shared/layout/MobileBottomBar/MobileBottomBar";

const vazirmatn = localFont({
  src: "../public/fonts/Vazirmatn/Vazirmatn-Regular.ttf",
  display: "swap",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html dir="rtl" lang="en">
      <body className={`${vazirmatn.className} antialiased`}>
        <Header />

        {children}
        <Footer />
        <MobileBottomBar />
      </body>
    </html>
  );
}
